runtime: java17
instance_class: F1

entrypoint: java -jar monitor-1.0-SNAPSHOT.jar

automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 30ms
  max_pending_latency: 300ms

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300